### ISSUE TITLE
Change Mumbai RPC provider

### ISSUE THREAD

**Issue by freitasgouvea** [solid-world/solid-world-marketplace-backend#117]
I've checked that probably the RPC we are using on Polygon Testnet Mumbai is not working. In the last deploy it didn't work and according to the logs since the may 7th it's not working properly. It would be nice to use another RPC or maybe start to use Alchemy as provider.

The error of the last deployment pipeline was this:

```
err: (node:57327) UnhandledPromiseRejectionWarning: Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.5.1)
err:     at Logger.makeError (node_modules/@ethersproject/logger/lib/index.js:199:21)
err:     at Logger.throwError (node_modules/@ethersproject/logger/lib/index.js:208:20)
err:     at JsonRpcProvider.<anonymous> (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:517:54)
err:     at step (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
err:     at Object.throw (node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
err:     at rejected (***node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
err:     at process._tickCallback (internal/process/next_tick.js:68:7)
```

We are using this RPC: `https://rpc-mumbai.maticvigil.com`

The available RPCs can be found in the documentation:

https://docs.polygon.technology/docs/develop/network-details/network/

**Comment by freitasgouvea** [comment]
We changed the RPC to `https://rpc-mumbai.matic.today/` and it is working again. I will close this issue.

**Comment by jeffprestes** [comment]
RPC Server at https://matic-mumbai.chainstacklabs.com is working

**Comment by raaha** [comment]
The RPC Servers was update to https://matic-mumbai.chainstacklabs.com/  yesterday May 11
