### ISSUE TITLE
Adjust API to new Marketplace Smart Contracts

### ISSUE THREAD

**Issue by jeffprestes** [solid-world/solid-world-marketplace-backend#89]
Due adjustments implemented at https://github.com/solid-world/solid-world-marketplace-contracts/pull/32 the API software must be adjusted.

Important: when use new contract please:
- access the marketplace database 
- make a backup of all tables
- execute `update` commands to reuse all "test" data informed into Database (project name, project description, imagens, etc). It is simple: just adjust the old Project/NFT/Carbon Credit to new IDs.

Please, @lucasdcoutinh0 , inform here the list of old projects ID that have good data and are shown at marketplace frontend

**Comment by freitasgouvea** [comment]
I finished the update of our database and created the selected projects in our test smart contract https://mumbai.polygonscan.com/address/0x9471eC86C4f8fBbd793E2C9dA53e21a58511C836
